### ISSUE TITLE
dsgrid Container seems to have limited capability

### ISSUE THREAD

**Issue by lixiliu** [dsgrid/dsgrid#109]
Semi-related: Is there a way to launch an interactive session with a spark cluster on Eagle?

1. `pytest` not available inside the container.
2. CLI commands requiring AWS credentials does not appear to work inside the dsgrid container:

Launch a singularity shell per instruction in `dsgrid container` section: https://github.com/dsgrid/dsgrid/tree/main/dev

I can do: `Singularity> dsgrid registry --help`
But not: `Singularity> dsgrid registry list`

Error:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 402, in ssl_wrap_socket
    context.load_verify_locations(ca_certs, ca_cert_dir, ca_cert_data)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/botocore/httpsession.py", line 385, in send
    urllib_response = conn.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py", line 507, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.8/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 416, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 404, in ssl_wrap_socket
    raise SSLError(e)
urllib3.exceptions.SSLError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/dsgrid", line 33, in <module>
    sys.exit(load_entry_point('dsgrid', 'console_scripts', 'dsgrid')())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1656, in invoke
    super().invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/repos/dsgrid/dsgrid/cli/registry.py", line 76, in registry
    ctx.obj = RegistryManager.load(
  File "/repos/dsgrid/dsgrid/registry/registry_manager.py", line 170, in load
    lock_files = list(cloud_interface.get_lock_files())
  File "/usr/local/lib/python3.8/site-packages/s3path.py", line 694, in glob
    yield from super().glob(pattern)
  File "/usr/local/lib/python3.8/pathlib.py", line 1140, in glob
    for p in selector.select_from(self):
  File "/usr/local/lib/python3.8/pathlib.py", line 587, in _select_from
    for p in successor_select(starting_point, is_dir, exists, scandir):
  File "/usr/local/lib/python3.8/pathlib.py", line 535, in _select_from
    entries = list(scandir_it)
  File "/usr/local/lib/python3.8/site-packages/s3path.py", line 123, in __iter__
    response = bucket.meta.client.list_objects_v2(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/botocore/client.py", line 391, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.8/site-packages/botocore/client.py", line 705, in _make_api_call
    http, parsed_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/botocore/client.py", line 725, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/usr/local/lib/python3.8/site-packages/botocore/endpoint.py", line 104, in make_request
    return self._send_request(request_dict, operation_model)
  File "/usr/local/lib/python3.8/site-packages/botocore/endpoint.py", line 138, in _send_request
    while self._needs_retry(attempts, operation_model, request_dict,
  File "/usr/local/lib/python3.8/site-packages/botocore/endpoint.py", line 254, in _needs_retry
    responses = self._event_emitter.emit(
  File "/usr/local/lib/python3.8/site-packages/botocore/hooks.py", line 357, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "/usr/local/lib/python3.8/site-packages/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/botocore/retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "/usr/local/lib/python3.8/site-packages/botocore/retryhandler.py", line 250, in __call__
    should_retry = self._should_retry(attempt_number, response,
  File "/usr/local/lib/python3.8/site-packages/botocore/retryhandler.py", line 277, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/usr/local/lib/python3.8/site-packages/botocore/retryhandler.py", line 316, in __call__
    checker_response = checker(attempt_number, response,
  File "/usr/local/lib/python3.8/site-packages/botocore/retryhandler.py", line 222, in __call__
    return self._check_caught_exception(
  File "/usr/local/lib/python3.8/site-packages/botocore/retryhandler.py", line 359, in _check_caught_exception
    raise caught_exception
  File "/usr/local/lib/python3.8/site-packages/botocore/endpoint.py", line 201, in _do_get_response
    http_response = self._send(request)
  File "/usr/local/lib/python3.8/site-packages/botocore/endpoint.py", line 270, in _send
    return self.http_session.send(request)
  File "/usr/local/lib/python3.8/site-packages/botocore/httpsession.py", line 412, in send
    raise SSLError(endpoint_url=request.url, error=e)
botocore.exceptions.SSLError: SSL validation failed for https://nrel-dsgrid-registry.s3.amazonaws.com/?list-type=2&prefix=&delimiter=%2F&encoding-type=url [Errno 2] No such file or directory
```

If you launch  a Spark cluster on Eagle via a jade-configured sleep job submission and then ssh into node, you can activate dsgrid env and do `dsgrid registry list` there.

**Comment by lixiliu** [comment]
From notebook:
```
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
/usr/local/lib/python3.8/site-packages/urllib3/util/ssl_.py in ssl_wrap_socket(sock, keyfile, certfile, cert_reqs, ca_certs, server_hostname, ssl_version, ciphers, ssl_context, ca_cert_dir, key_password, ca_cert_data, tls_in_tls)
    401         try:
--> 402             context.load_verify_locations(ca_certs, ca_cert_dir, ca_cert_data)
    403         except (IOError, OSError) as e:

FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

SSLError                                  Traceback (most recent call last)
/usr/local/lib/python3.8/site-packages/botocore/httpsession.py in send(self, request)
    384             request_target = self._get_request_target(request.url, proxy_url)
--> 385             urllib_response = conn.urlopen(
    386                 method=request.method,

/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py in urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
    754 
--> 755             retries = retries.increment(
    756                 method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]

/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py in increment(self, method, url, response, error, _pool, _stacktrace)
    506             # Disabled, indicate to re-raise the error.
--> 507             raise six.reraise(type(error), error, _stacktrace)
    508 

/usr/local/lib/python3.8/site-packages/urllib3/packages/six.py in reraise(tp, value, tb)
    769                 raise value.with_traceback(tb)
--> 770             raise value
    771         finally:

/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py in urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
    698             # Make the request on the httplib connection object.
--> 699             httplib_response = self._make_request(
    700                 conn,

/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py in _make_request(self, conn, method, url, timeout, chunked, **httplib_request_kw)
    381         try:
--> 382             self._validate_conn(conn)
    383         except (SocketTimeout, BaseSSLError) as e:

/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py in _validate_conn(self, conn)
   1009         if not getattr(conn, "sock", None):  # AppEngine might not have  `.sock`
-> 1010             conn.connect()
   1011 

/usr/local/lib/python3.8/site-packages/urllib3/connection.py in connect(self)
    415 
--> 416         self.sock = ssl_wrap_socket(
    417             sock=conn,

/usr/local/lib/python3.8/site-packages/urllib3/util/ssl_.py in ssl_wrap_socket(sock, keyfile, certfile, cert_reqs, ca_certs, server_hostname, ssl_version, ciphers, ssl_context, ca_cert_dir, key_password, ca_cert_data, tls_in_tls)
    403         except (IOError, OSError) as e:
--> 404             raise SSLError(e)
    405 

SSLError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

SSLError                                  Traceback (most recent call last)
/tmp/ipykernel_78990/101546658.py in <module>
----> 1 registry = RegistryManager.load(os.getenv("DSGRID_REGISTRY_PATH", default=LOCAL_REGISTRY))

/repos/dsgrid/dsgrid/registry/registry_manager.py in load(cls, path, remote_path, offline_mode, dry_run_mode, user, no_prompts)
    168 
    169         if not offline_mode:
--> 170             lock_files = list(cloud_interface.get_lock_files())
    171             if lock_files:
    172                 msg = f"There are {len(lock_files)} lock files in the registry:"

/usr/local/lib/python3.8/site-packages/s3path.py in glob(self, pattern)
    692         yielding all matching files (of any kind)
    693         """
--> 694         yield from super().glob(pattern)
    695 
    696     def rglob(self, pattern):

/usr/local/lib/python3.8/pathlib.py in glob(self, pattern)
   1138             raise NotImplementedError("Non-relative patterns are unsupported")
   1139         selector = _make_selector(tuple(pattern_parts), self._flavour)
-> 1140         for p in selector.select_from(self):
   1141             yield p
   1142 

/usr/local/lib/python3.8/pathlib.py in _select_from(self, parent_path, is_dir, exists, scandir)
    585                 successor_select = self.successor._select_from
    586                 for starting_point in self._iterate_directories(parent_path, is_dir, scandir):
--> 587                     for p in successor_select(starting_point, is_dir, exists, scandir):
    588                         if p not in yielded:
    589                             yield p

/usr/local/lib/python3.8/pathlib.py in _select_from(self, parent_path, is_dir, exists, scandir)
    533         try:
    534             with scandir(parent_path) as scandir_it:
--> 535                 entries = list(scandir_it)
    536             for entry in entries:
    537                 if self.dironly:

/usr/local/lib/python3.8/site-packages/s3path.py in __iter__(self)
    121             if continuation_token:
    122                 kwargs['ContinuationToken'] = continuation_token
--> 123             response = bucket.meta.client.list_objects_v2(**kwargs)
    124             for folder in response.get('CommonPrefixes', ()):
    125                 full_name = folder['Prefix'][:-1] if folder['Prefix'].endswith(sep) else folder['Prefix']

/usr/local/lib/python3.8/site-packages/botocore/client.py in _api_call(self, *args, **kwargs)
    389                     "%s() only accepts keyword arguments." % py_operation_name)
    390             # The "self" in this scope is referring to the BaseClient.
--> 391             return self._make_api_call(operation_name, kwargs)
    392 
    393         _api_call.__name__ = str(py_operation_name)

/usr/local/lib/python3.8/site-packages/botocore/client.py in _make_api_call(self, operation_name, api_params)
    703             http, parsed_response = event_response
    704         else:
--> 705             http, parsed_response = self._make_request(
    706                 operation_model, request_dict, request_context)
    707 

/usr/local/lib/python3.8/site-packages/botocore/client.py in _make_request(self, operation_model, request_dict, request_context)
    723     def _make_request(self, operation_model, request_dict, request_context):
    724         try:
--> 725             return self._endpoint.make_request(operation_model, request_dict)
    726         except Exception as e:
    727             self.meta.events.emit(

/usr/local/lib/python3.8/site-packages/botocore/endpoint.py in make_request(self, operation_model, request_dict)
    102         logger.debug("Making request for %s with params: %s",
    103                      operation_model, request_dict)
--> 104         return self._send_request(request_dict, operation_model)
    105 
    106     def create_request(self, params, operation_model=None):

/usr/local/lib/python3.8/site-packages/botocore/endpoint.py in _send_request(self, request_dict, operation_model)
    136         success_response, exception = self._get_response(
    137             request, operation_model, context)
--> 138         while self._needs_retry(attempts, operation_model, request_dict,
    139                                 success_response, exception):
    140             attempts += 1

/usr/local/lib/python3.8/site-packages/botocore/endpoint.py in _needs_retry(self, attempts, operation_model, request_dict, response, caught_exception)
    252             service_id,
    253             operation_model.name)
--> 254         responses = self._event_emitter.emit(
    255             event_name, response=response, endpoint=self,
    256             operation=operation_model, attempts=attempts,

/usr/local/lib/python3.8/site-packages/botocore/hooks.py in emit(self, event_name, **kwargs)
    355     def emit(self, event_name, **kwargs):
    356         aliased_event_name = self._alias_event_name(event_name)
--> 357         return self._emitter.emit(aliased_event_name, **kwargs)
    358 
    359     def emit_until_response(self, event_name, **kwargs):

/usr/local/lib/python3.8/site-packages/botocore/hooks.py in emit(self, event_name, **kwargs)
    226                  handlers.
    227         """
--> 228         return self._emit(event_name, kwargs)
    229 
    230     def emit_until_response(self, event_name, **kwargs):

/usr/local/lib/python3.8/site-packages/botocore/hooks.py in _emit(self, event_name, kwargs, stop_on_response)
    209         for handler in handlers_to_call:
    210             logger.debug('Event %s: calling handler %s', event_name, handler)
--> 211             response = handler(**kwargs)
    212             responses.append((handler, response))
    213             if stop_on_response and response is not None:

/usr/local/lib/python3.8/site-packages/botocore/retryhandler.py in __call__(self, attempts, response, caught_exception, **kwargs)
    181 
    182         """
--> 183         if self._checker(attempts, response, caught_exception):
    184             result = self._action(attempts=attempts)
    185             logger.debug("Retry needed, action of: %s", result)

/usr/local/lib/python3.8/site-packages/botocore/retryhandler.py in __call__(self, attempt_number, response, caught_exception)
    248 
    249     def __call__(self, attempt_number, response, caught_exception):
--> 250         should_retry = self._should_retry(attempt_number, response,
    251                                           caught_exception)
    252         if should_retry:

/usr/local/lib/python3.8/site-packages/botocore/retryhandler.py in _should_retry(self, attempt_number, response, caught_exception)
    275             # If we've exceeded the max attempts we just let the exception
    276             # propogate if one has occurred.
--> 277             return self._checker(attempt_number, response, caught_exception)
    278 
    279 

/usr/local/lib/python3.8/site-packages/botocore/retryhandler.py in __call__(self, attempt_number, response, caught_exception)
    314     def __call__(self, attempt_number, response, caught_exception):
    315         for checker in self._checkers:
--> 316             checker_response = checker(attempt_number, response,
    317                                        caught_exception)
    318             if checker_response:

/usr/local/lib/python3.8/site-packages/botocore/retryhandler.py in __call__(self, attempt_number, response, caught_exception)
    220             return self._check_response(attempt_number, response)
    221         elif caught_exception is not None:
--> 222             return self._check_caught_exception(
    223                 attempt_number, caught_exception)
    224         else:

/usr/local/lib/python3.8/site-packages/botocore/retryhandler.py in _check_caught_exception(self, attempt_number, caught_exception)
    357         # the MaxAttemptsDecorator is not interested in retrying the exception
    358         # then this exception just propogates out past the retry code.
--> 359         raise caught_exception

/usr/local/lib/python3.8/site-packages/botocore/endpoint.py in _do_get_response(self, request, operation_model)
    199             http_response = first_non_none_response(responses)
    200             if http_response is None:
--> 201                 http_response = self._send(request)
    202         except HTTPClientError as e:
    203             return (None, e)

/usr/local/lib/python3.8/site-packages/botocore/endpoint.py in _send(self, request)
    268 
    269     def _send(self, request):
--> 270         return self.http_session.send(request)
    271 
    272 

/usr/local/lib/python3.8/site-packages/botocore/httpsession.py in send(self, request)
    410             return http_response
    411         except URLLib3SSLError as e:
--> 412             raise SSLError(endpoint_url=request.url, error=e)
    413         except (NewConnectionError, socket.gaierror) as e:
    414             raise EndpointConnectionError(endpoint_url=request.url, error=e)

SSLError: SSL validation failed for https://nrel-dsgrid-registry.s3.amazonaws.com/?list-type=2&prefix=&delimiter=%2F&encoding-type=url [Errno 2] No such file or directory
```
