### ISSUE TITLE
dsgrid registry error

### ISSUE THREAD

**Issue by elainethale** [dsgrid/dsgrid#111]
Right now when I try to load the dsgrid registry from the main branch I get this error:

```
There are 1 lock files in the registry:
	- /nrel-dsgrid-registry/configs/.locks
... Do you want to continue syncing the registry contents? [Y] >>> y

Failed to validate /scratch/ehale/.dsgrid-registry/configs/dimension_mappings/conus_2022-resstock_energy_enduses_kwh__conus-2022-detailed-end-uses-kwh__5abd7f24-3ed9-4457-a609-2b20d1b63e5f/1.0.0/dimension_mapping.toml
Traceback (most recent call last):
  File "/home/ehale/dsgrid/dsgrid/data_models.py", line 49, in load
    cfg = cls(**load_data(filename.name))
  File "pydantic/main.py", line 406, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 2 validation errors for AssociationTableModel
archetype
  extra fields not permitted (type=value_error.extra)
mapping_type
  extra fields not permitted (type=value_error.extra)

---------------------------------------------------------------------------
ValidationError                           Traceback (most recent call last)
/tmp/ipykernel_70015/2261966118.py in <module>
      4 from dsgrid.registry.registry_manager import RegistryManager
      5 
----> 6 registry = RegistryManager.load(os.getenv("DSGRID_REGISTRY_PATH", default=LOCAL_REGISTRY))

~/dsgrid/dsgrid/registry/registry_manager.py in load(cls, path, remote_path, offline_mode, dry_run_mode, user, no_prompts)
    222             dry_run_mode,
    223         )
--> 224         return cls(params)
    225 
    226     def data_sync(self, project_id, dataset_id, no_prompts=True):

~/dsgrid/dsgrid/registry/registry_manager.py in __init__(self, params)
     57             params.base_path / DimensionRegistry.registry_path(), params
     58         )
---> 59         self._dimension_mapping_dimension_mgr = DimensionMappingRegistryManager.load(
     60             params.base_path / DimensionMappingRegistry.registry_path(),
     61             params,

~/dsgrid/dsgrid/registry/dimension_mapping_registry_manager.py in load(cls, path, fs_interface, dimension_manager)
     40     @classmethod
     41     def load(cls, path, fs_interface, dimension_manager):
---> 42         mgr = cls._load(path, fs_interface)
     43         mgr.dimension_manager = dimension_manager
     44         return mgr

~/dsgrid/dsgrid/registry/registry_manager_base.py in _load(cls, path, fs_interface)
     62     def _load(cls, path, fs_interface):
     63         mgr = cls(path, fs_interface)
---> 64         mgr.inventory()
     65         return mgr
     66 

~/dsgrid/dsgrid/registry/dimension_mapping_registry_manager.py in inventory(self)
     51             registry = self.registry_class().load(map_path / REGISTRY_FILENAME)
     52             self._registry_configs[map_id] = registry
---> 53             registry_config = self.get_by_id(map_id)
     54             self._id_to_type[map_id] = [
     55                 registry_config.model.from_dimension.dimension_type,

~/dsgrid/dsgrid/registry/dimension_mapping_registry_manager.py in get_by_id(self, config_id, version)
    156             version = self._registry_configs[config_id].model.version
    157         key = ConfigKey(config_id, version)
--> 158         return self.get_by_key(key)
    159 
    160     def get_by_key(self, key):

~/dsgrid/dsgrid/registry/dimension_mapping_registry_manager.py in get_by_key(self, key)
    167 
    168         filename = self.get_config_file(key.id, key.version)
--> 169         config = AssociationTableConfig.load(filename)
    170         self._mappings[key] = config
    171         return config

~/dsgrid/dsgrid/config/config_base.py in load(cls, config_file)
    113     @classmethod
    114     def load(cls, config_file):
--> 115         config = super().load(config_file)
    116         config.src_dir = os.path.dirname(config_file)
    117         return config

~/dsgrid/dsgrid/config/config_base.py in load(cls, config_file, *args, **kwargs)
     34         """
     35         # Subclasses can reimplement this method if they need more arguments.
---> 36         return cls._load(config_file)
     37 
     38     @classmethod

~/dsgrid/dsgrid/config/config_base.py in _load(cls, config_file)
     38     @classmethod
     39     def _load(cls, config_file):
---> 40         model = cls.model_class().load(config_file)
     41         return cls(model)
     42 

~/dsgrid/dsgrid/data_models.py in load(cls, filename)
     47         os.chdir(base_dir)
     48         try:
---> 49             cfg = cls(**load_data(filename.name))
     50             return cfg
     51         except ValidationError:

~/environments/dsgrid/lib/python3.8/site-packages/pydantic/main.cpython-38-x86_64-linux-gnu.so in pydantic.main.BaseModel.__init__()

ValidationError: 2 validation errors for AssociationTableModel
archetype
  extra fields not permitted (type=value_error.extra)
mapping_type
  extra fields not permitted (type=value_error.extra)

registry.dataset_manager.show()
```

@mooneyme @lixiliu @daniel-thom

**Comment by elainethale** [comment]
Also currently when I tell it not to sync it still fails:

```
There are 1 lock files in the registry:
	- /nrel-dsgrid-registry/configs/.locks
... Do you want to continue syncing the registry contents? [Y] >>> N

---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
/tmp/ipykernel_70015/975771507.py in <module>
      6 registry_path = os.getenv("DSGRID_REGISTRY_PATH", default=LOCAL_REGISTRY)
      7 logging.info(f"Loading dsgrid registry from {registry_path}")
----> 8 registry = RegistryManager.load(registry_path)

~/dsgrid/dsgrid/registry/registry_manager.py in load(cls, path, remote_path, offline_mode, dry_run_mode, user, no_prompts)
    187                 sync = True
    188 
--> 189             if sync:
    190                 logger.info("Sync configs from remote registry.")
    191                 # NOTE: When creating a registry, only the /configs are pulled. To sync_pull /data, use the dsgrid registry data-sync CLI command.

UnboundLocalError: local variable 'sync' referenced before assignment
```

**Comment by daniel-thom** [comment]
Looks like dsgrid code is working correctly. These fields are new to Lixi's branch.
```
pydantic.error_wrappers.ValidationError: 2 validation errors for AssociationTableModel
archetype
  extra fields not permitted (type=value_error.extra)
mapping_type
  extra fields not permitted (type=value_error.extra
```

**Comment by daniel-thom** [comment]
Why is there a lock file in the registry? Did someone's process crash?

**Comment by lixiliu** [comment]
Not sure why there's been a lock file but it's been there for a while. I registered a new dimension_mapping () that's required for Standard Scenario's ResStock and ComStock using my branch so the config for that dim contains the extra fields. It's `mapping_id=conus_2022-resstock_energy_enduses_kwh__conus-2022-detailed-end-uses-kwh__5abd7f24-3ed9-4457-a609-2b20d1b63e5f`

**Comment by daniel-thom** [comment]
Yeah, we need a rule that anything in the registry needs to be based on the main branches. Feature branches need to create local registries for testing. We can use scripts like make_standard_scenarios_registry.py and make_us_data_registry.py for that.

**Comment by lixiliu** [comment]
Sorry. Done, I removed the fields in the new dim mapping for now. Also removed the lock file, it was a `tempo_conus_2022.lock`.
