### ISSUE TITLE
Pydantic validation error provides no information on what failed

### ISSUE THREAD

**Issue by elainethale** [dsgrid/dsgrid#39]
My guess is that a path is wrong in my dataset.toml, but the error doesn't say so:

```
(dsgrid) ehale@EHALE-32272S:~/dsgrid$ dsgrid registry --path=$DSGRID_REGISTRY_PATH --offline datasets register $US_DATA_REPO/dsgrid_project/datasets/sector_models/comstock/dataset.toml -l "initial registration"
2021-05-21 10:02:52,087 - INFO [dsgrid.registry.registry_manager registry_manager.py:199] : Loaded local registry at /home/ehale/.dsgrid-test-registry offline_mode=True dry_run_mode=False
Traceback (most recent call last):
  File "/home/ehale/miniconda3/envs/dsgrid/bin/dsgrid", line 33, in <module>
    sys.exit(load_entry_point('dsgrid', 'console_scripts', 'dsgrid')())
  File "/home/ehale/miniconda3/envs/dsgrid/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/ehale/miniconda3/envs/dsgrid/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/ehale/miniconda3/envs/dsgrid/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ehale/miniconda3/envs/dsgrid/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ehale/miniconda3/envs/dsgrid/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ehale/miniconda3/envs/dsgrid/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ehale/miniconda3/envs/dsgrid/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/ehale/miniconda3/envs/dsgrid/lib/python3.8/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/home/ehale/dsgrid/dsgrid/cli/registry.py", line 265, in register_dataset
    manager.register(dataset_config_file, submitter, log_message)
  File "/home/ehale/dsgrid/dsgrid/registry/dataset_registry_manager.py", line 82, in register
    self._register(config_file, submitter, log_message, force=force)
  File "/home/ehale/dsgrid/dsgrid/registry/dataset_registry_manager.py", line 85, in _register
    config = DatasetConfig.load(config_file, self._dimension_mgr)
  File "/home/ehale/dsgrid/dsgrid/config/dataset_config.py", line 157, in load
    config = cls._load(config_file)
  File "/home/ehale/dsgrid/dsgrid/config/config_base.py", line 29, in _load
    model = cls.model_class().load(config_file)
  File "/home/ehale/dsgrid/dsgrid/data_models.py", line 40, in load
    cfg = cls(**load_data(os.path.basename(filename)))
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for DatasetConfigModel
path
  /home/ehale/.dsgrid-registry/data/efs-comstock/1.0.0 does not contain load_data.parquet (type=value_error)
(dsgrid) ehale@EHALE-32272S:~/dsgrid$
```

**Comment by elainethale** [comment]
@mooneyme the underlying cause for this error (bad data syncing) has been fixed. Do we still want a more informative message if the dataset.toml data path and the actual location of the data file get out of sync and/or the data file goes missing?

**Comment by mooneyme** [comment]
I think you can close this. The message at the end is informative I think: "`  /home/ehale/.dsgrid-registry/data/efs-comstock/1.0.0 does not contain load_data.parquet (type=value_error)`"
